name: Traffic

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: npm install

      - name: Configure kubectl for EKS
        run: aws eks update-kubeconfig --name EksCluster --region us-east-1

      - name: Download and install istioctl
        run: |
          ISTIO_VERSION=1.22.0
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$ISTIO_VERSION sh -
          sudo mv istio-$ISTIO_VERSION/bin/istioctl /usr/local/bin/
          istioctl version

      - name: Install Istio CRDs
        run: istioctl install --set profile=default --set components.operator.enabled=true --skip-confirmation

      - name: Apply IstioOperator manifest
        run: istioctl install -f ./path/to/istio-operator.yaml --skip-confirmation

      - name: Bootstrap CDK (if needed)
        run: cdk bootstrap

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
