name: Traffic

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: actions/setup-kubectl@v2
        with:
          version: 'latest'

      - name: Configure kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}  
        run: |
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Install Istio CRDs
        run: |
          kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/manifests/crd.yaml

      - name: Setup CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: npm install

      - name: Bootstrap CDK (if needed)
        run: cdk bootstrap

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
